# RuboCop configuration file
# See https://docs.rubocop.org/rubocop/configuration

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'coverage/**/*'
    - 'spec/dummy/**/*'

# Style
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 5

Metrics/PerceivedComplexity:
  Max: 5

# Lint
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# RSpec
require:
  - rubocop-rspec

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 3

# Disable problematic cops
Capybara/RSpec/PredicateMatcher:
  Enabled: false
